name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install gcc-11

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      
    - name: Watching folder
      run: ls

    - name: Configure build
      run: qmake -o Makefile Project.pro

    - name: Build project
      run: make

    - name: Run project
      run: ./Project

