name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: qt-actions/setup-qt@v1
      with:
        qt-version: '6.2.4'

    - name: Set up GCC
      uses: actions/setup-gcc-toolchain@v2
      with:
        gcc-version: '11'

    - name: Configure build
      run: qmake -o Makefile ./project.pro

    - name: Build project
      run: make

    - name: Run project
      run: ./project
