name: Build on Ubuntu with Qt
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Qt
        uses: qt-actions/setup-qt@v3
        with:
          qt-version: '6.2.4'

      - name: Set up qmake
        run: sudo apt-get install -y qttools5-dev-tools

      - name: Set up GCC
        uses: actions/setup-gcc@v2
        with:
          gcc-version: '11.3'

      - name: Build project
        run: |
          mkdir build
          cd build
          qmake ..
          make
