name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install gcc-11

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
        cache: 'true'
      
    - name: Watching folder
      run: ls
      
    - name: Check Qt version
      run: qmake --version

    - name: Configure build
      run: qmake -o Makefile Project.pro

    - name: Build project
      run: make

