name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install gcc-11

    - name: Install Qt
      run: |
        sudo apt-get install -y qt6-default
        sudo apt-get install -y qt6-qmake
        sudo apt-get install -y qt6-base
        sudo apt-get install -y qt6-x11extras

    - name: Configure build
      run: qmake -o Makefile ./project.pro

    - name: Build project
      run: make

    - name: Run project
      run: ./project

